basePath: /
definitions:
  models.Storage:
    properties:
      articleID:
        type: integer
      bestand:
        type: integer
      name:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: justin.kromlinger@stud.htwk-leipzig.de
    name: Justin Kromlinger
    url: https://hashworks.net
  description: Solution for 'Lager' backend task of https://sites.google.com/relaxdays.de/hackathon-relaxdays/startseite#h.n7504a3wvsj5
  license:
    name: GNU Affero General Public License v3
    url: https://gnu.org/licenses/agpl.html
  title: Storage Backend Task
  version: "1.0"
paths:
  /storagePlace:
    delete:
      parameters:
      - description: Name of storage to delete
        in: query
        name: x
        required: true
        type: string
      responses:
        "204":
          description: ""
      summary: Delete a storage by name
      tags:
      - Storage
    get:
      parameters:
      - description: Name of storage to retrieve
        in: query
        name: x
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Storage'
        "404":
          description: Storage not found
          schema:
            type: ""
      summary: Returns a specifc storage by name
      tags:
      - Storage
  /storagePlace/:
    post:
      parameters:
      - description: Storage to Update
        in: body
        name: storage
        required: true
        schema:
          $ref: '#/definitions/models.Storage'
      responses:
        "200":
          description: ""
        "400":
          description: Invalid storage
          schema:
            type: ""
      summary: Update a storage
      tags:
      - Storage
    put:
      parameters:
      - description: Storage to save
        in: body
        name: storage
        required: true
        schema:
          $ref: '#/definitions/models.Storage'
      responses:
        "200":
          description: ""
        "400":
          description: Invalid storage
          schema:
            type: ""
      summary: Save a storage
      tags:
      - Storage
  /storagesPlaces:
    get:
      parameters:
      - description: Number of storages after the named one
        in: query
        name: "n"
        required: true
        type: integer
      - description: Storage name where we should start the cursor
        in: query
        name: x
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Storage'
            type: array
      summary: Returns "n" storages lexicographically after storage "name"
      tags:
      - Storage
swagger: "2.0"
